services:
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: rade-app-prod-image:latest
    container_name: rade-app-prod
    environment:
      - no_proxy=localhost,127.0.0.1,llama-gpu,llama-gpu-2,llama-cpu,.parana,pr.gov.br
      - NO_PROXY=localhost,127.0.0.1,llama-gpu,llama-gpu-2,llama-cpu,.parana,pr.gov.br
    ports:
      - "8000:8000"
    networks:
      - rade_net

  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: rafaelaugustodocumentoextratorrade-app
    container_name: rade-app-dev
    ports:
      - "8080:8000" 
    volumes:
      - .:/app
    networks:
      - rade_net
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

networks:
  rade_net:
    external: true