services:
  llama-gpu:
    build: 
      context: .
      dockerfile: Dockerfile
    image: rafaelaugustodocumentoextratorrade-app
    command: ["python", "-m", "llama_cpp.server", "--model", "./app/models/phi_pt_q4_k_m.gguf", "--n_gpu_layers", "-1", "--n_ctx", "4096", "--flash_attn", "True", "--host", "0.0.0.0", "--port", "8001"]
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    networks:
      - rade_net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  llama-gpu-2:
    image: rafaelaugustodocumentoextratorrade-app
    command: ["python", "-m", "llama_cpp.server", "--model", "./app/models/phi_pt_q4_k_m.gguf", "--n_gpu_layers", "-1", "--n_ctx", "4096", "--flash_attn", "True", "--host", "0.0.0.0", "--port", "8003"]
    ports:
      - "8003:8003"
    volumes:
      - .:/app
    networks:
      - rade_net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  llama-cpu:
    image: rafaelaugustodocumentoextratorrade-app
    command: ["python", "-m", "llama_cpp.server", "--model", "./app/models/phi_pt_q4_k_m.gguf", "--n_gpu_layers", "0", "--n_ctx", "4096", "--flash_attn", "True", "--host", "0.0.0.0", "--port", "8002"]
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    networks:
      - rade_net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  rade_net:
    external: true